# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: ko

# Timezone
timezone: Asia/Seoul

# jekyll-seo-tag settings
title: Vertica
tagline: Vertica DBA 기술 블로그
description: >-
  Vertica 데이터베이스 관리, 최적화, 튜토리얼

# Site URL
url: "https://Komina537.github.io"
baseurl: ""

# GitHub
github:
  username: Komina537

# Social
twitter:
  username: null  # 없으면 null
social:
  name: Komina
  email: komina537@example.com  # 네 이메일
  links:
    - https://github.com/Komina537

# CDN
cdn: "https://chirpy-img.netlify.app"

# Avatar
avatar: "/assets/img/avatar.jpg"  # assets/img/에 사진 넣어

# TOC
toc: true

# Comments (나중에 설정)
comments:
  provider: null

# PWA
pwa:
  enabled: true

# Pagination
paginate: 10

# Kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Collections
collections:
  tabs:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false

# Sass
sass:
  style: compressed

# Compress HTML
compress_html:
  clippings: all
  comments: all

# Exclude
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# Jekyll Archives
jekyll-archives:
  enabled: [categories/tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
